/// <reference path="../pb_data/types.d.ts" />
migrate(
	(app) => {
		const collection = new Collection({
			id: "pbc_1598076546",
			listRule: null,
			viewRule: null,
			createRule: null,
			updateRule: null,
			deleteRule: null,
			name: "tasks",
			type: "base",
			fields: [
				{
					autogeneratePattern: "[a-z0-9]{15}",
					hidden: false,
					id: "text3208210256",
					max: 15,
					min: 15,
					name: "id",
					pattern: "^[a-z0-9]+$",
					presentable: false,
					primaryKey: true,
					required: true,
					system: true,
					type: "text",
				},
				{
					autogeneratePattern: "",
					hidden: false,
					id: "text724990059",
					max: 0,
					min: 0,
					name: "title",
					pattern: "",
					presentable: false,
					primaryKey: false,
					required: false,
					system: false,
					type: "text",
				},
				{
					convertURLs: false,
					hidden: false,
					id: "editor1843675174",
					maxSize: 0,
					name: "description",
					presentable: false,
					required: false,
					system: false,
					type: "editor",
				},
				{
					hidden: false,
					id: "bool989355118",
					name: "completed",
					presentable: false,
					required: false,
					system: false,
					type: "bool",
				},
				{
					hidden: false,
					id: "date2566134982",
					max: "",
					min: "",
					name: "allocated_date",
					presentable: false,
					required: true,
					system: false,
					type: "date",
				},
				{
					hidden: false,
					id: "date3866337329",
					max: "",
					min: "",
					name: "due_date",
					presentable: false,
					required: false,
					system: false,
					type: "date",
				},
				{
					hidden: false,
					id: "number68578651",
					max: null,
					min: null,
					name: "carry_over",
					onlyInt: true,
					presentable: false,
					required: false,
					system: false,
					type: "number",
				},
				{
					hidden: false,
					id: "number4113142680",
					max: null,
					min: null,
					name: "order",
					onlyInt: false,
					presentable: false,
					required: false,
					system: false,
					type: "number",
				},
				{
					hidden: false,
					id: "autodate2990389176",
					name: "created",
					onCreate: true,
					onUpdate: false,
					presentable: false,
					system: false,
					type: "autodate",
				},
				{
					hidden: false,
					id: "autodate3332085495",
					name: "updated",
					onCreate: true,
					onUpdate: true,
					presentable: false,
					system: false,
					type: "autodate",
				},
			],
			indexes: [
				"CREATE INDEX `idx_UWolL3pxbS` ON `tasks` (`allocated_date`)",
				"CREATE INDEX `idx_UgOE0d0hrA` ON `tasks` (`completed`)",
			],
			system: false,
		})

		return app.save(collection)
	},
	(app) => {
		const collection = app.findCollectionByNameOrId("pbc_1598076546")

		return app.delete(collection)
	},
)
